/**
 * Custom block material with advanced shaders
 * Replaces basic MeshStandardMaterial with enhanced lighting and effects
 */

import * as THREE from 'three';

function createWhiteTexture(): THREE.DataTexture {
  const texture = new THREE.DataTexture(new Uint8Array([255, 255, 255, 255]), 1, 1, THREE.RGBAFormat, THREE.UnsignedByteType);
  texture.needsUpdate = true;
  texture.colorSpace = THREE.NoColorSpace;
  return texture;
}

export class BlockMaterial extends THREE.ShaderMaterial {
  constructor(
    albedoTexture: THREE.Texture,
    envMap: THREE.CubeTexture | null,
    normalMap?: THREE.Texture,
    atlasInfo?: { tileSize: number; atlasSize: number }
  ) {
    const vertexShader = `
      // Block vertex shader using per-vertex tint and ambient occlusion
      #include <common>
      attribute vec3 color;
      attribute float ao;
      varying vec3 vColor;
      varying vec2 vUv;
      varying vec3 vNormal;
      varying vec3 vWorldPosition;
      varying vec3 vViewPosition;
      varying float vAmbientOcclusion;

      void main() {
          vUv = uv;
          // Lighting uniforms and world position are world-space. Chunk and
          // seabed meshes only use rigid transforms, so modelMatrix is the
          // correct normal transform here; normalMatrix would be view-space.
          vNormal = normalize(mat3(modelMatrix) * normal);
          vColor = color;
          vAmbientOcclusion = clamp(ao, 0.0, 1.0);
          
          vec4 worldPosition = modelMatrix * vec4(position, 1.0);
          vWorldPosition = worldPosition.xyz;
          
          vec4 viewPosition = viewMatrix * worldPosition;
          vViewPosition = viewPosition.xyz;

          gl_Position = projectionMatrix * viewPosition;
      }
    `;

    const fragmentShader = `
      #include <common>
      uniform sampler2D voxelShadowMask;
      uniform sampler2D voxelShadowDepth;
      uniform vec2 voxelShadowResolution;
      uniform float voxelShadowCameraNear;
      uniform float voxelShadowCameraFar;
      uniform bool voxelShadowEnabled;
      varying vec3 vViewPosition;
      // Sun visibility is generated by VoxelSunShadowPass. It is sampled in
      // screen space so every terrain fragment uses the same receiver result;
      // there is deliberately no native shadow-map projection or bias here.
      float sampleVoxelShadow(vec2 uv) {
        return texture2D(voxelShadowMask, clamp(uv, vec2(0.0), vec2(1.0))).r;
      }

      float decodeVoxelShadowDepth(float raw) {
        if (raw >= 0.999999) return voxelShadowCameraFar;
        return (voxelShadowCameraNear * voxelShadowCameraFar) /
          ((voxelShadowCameraFar - voxelShadowCameraNear) * raw - voxelShadowCameraFar);
      }

      float sampleVoxelShadowDepth(vec2 uv) {
        return -decodeVoxelShadowDepth(texture2D(voxelShadowDepth, clamp(uv, vec2(0.0), vec2(1.0))).r);
      }

      float shadowNeighbourWeight(vec2 uv, float referenceDepth) {
        float neighbourDepth = sampleVoxelShadowDepth(uv);
        float tolerance = max(0.025, referenceDepth * 0.015);
        return 1.0 - smoothstep(tolerance, tolerance * 4.0, abs(neighbourDepth - referenceDepth));
      }

      float getVoxelShadowMask() {
        if (!voxelShadowEnabled) return 1.0;
        // gl_FragCoord is already at the pixel centre.  The former extra
        // half-pixel offset put nearest samples on texel boundaries.
        vec2 uv = gl_FragCoord.xy / max(voxelShadowResolution, vec2(1.0));
        float center = sampleVoxelShadow(uv);
        // The solar-disc integration is intentionally adaptive, so this is
        // only a small reconstruction of the remaining 1/21-level contouring.
        // Neighbours are accepted only when their prepass depth agrees with
        // this fragment; silhouettes therefore cannot bleed across geometry.
        float uncertainty = smoothstep(0.02, 0.98, 4.0 * center * (1.0 - center));
        if (uncertainty <= 0.0) return center;
        vec2 texel = 1.0 / max(voxelShadowResolution, vec2(1.0));
        float referenceDepth = -vViewPosition.z;
        vec2 offsets[4];
        offsets[0] = vec2(texel.x, 0.0);
        offsets[1] = vec2(-texel.x, 0.0);
        offsets[2] = vec2(0.0, texel.y);
        offsets[3] = vec2(0.0, -texel.y);
        float weighted = 0.0;
        float weightSum = 0.0;
        for (int i = 0; i < 4; i++) {
          float weight = shadowNeighbourWeight(uv + offsets[i], referenceDepth);
          weighted += sampleVoxelShadow(uv + offsets[i]) * weight;
          weightSum += weight;
        }
        if (weightSum <= 1e-4) return center;
        float neighbours = weighted / weightSum;
        return mix(center, neighbours, 0.55 * uncertainty);
      }

      varying vec2 vUv;
      varying vec3 vNormal;
      varying vec3 vWorldPosition;
      varying vec3 vColor;
      varying float vAmbientOcclusion;

      uniform sampler2D map;
      uniform sampler2D normalMap;
      uniform samplerCube envMap;
      uniform float roughness;
      uniform float metalness;
      uniform float envMapIntensity;
      uniform float alphaScale;
      uniform float lightingMix;

      // Anti-aliasing controls
      uniform bool aaEnabled;
      uniform float aaStrength;   // 0..1
      uniform bool aaLodBiasEnabled; // use explicit LOD bias for non-atlas textures
      uniform float aaLodBias;    // 0..2 typically
      uniform float atlasSize;    // tiles across (U). 1.0 if not using atlas
      uniform float tileSize;     // texels per tile (square)
      uniform float ditherAmount; // 0..1 strength in sRGB LDR (approx 1 LSB at 1.0)
      
      // Sun uniforms (directional light driven by SunController)
      uniform vec3 sunDirection;
      uniform vec3 sunColor;

      // Day/night factor (0=night, 1=day)
      uniform float dayLight;
      // Star light factor (0..1) tiny ambient boost at night
      uniform float starLight;
      // Scene-linear irradiance evaluated by AtmosphereModel.
      uniform vec3 skyAmbient;

      // Optional water-caustic contribution. Disabled by default so ordinary
      // block materials remain unchanged; WaterSystem enables it for the
      // playable and visual-only seabed surfaces.
      uniform bool waterCausticEnabled;
      uniform float waterCausticLevel;
      uniform float waterCausticIntensity;
      uniform float waterCausticTime;
      uniform sampler2D waterCausticMap;
      uniform bool waterCausticMapEnabled;
      uniform vec2 waterCausticOrigin;
      uniform float waterCausticExtent;
      uniform vec2 waterCausticResolution;

      // Specular anti-aliasing: broaden roughness near high normal gradients
      float specularAARoughness(float r, vec3 N) {
          // Variance from normal derivatives; clamp to avoid NaNs
          vec3 dnx = dFdx(N);
          vec3 dny = dFdy(N);
          float variance = max(dot(dnx, dnx), dot(dny, dny));
          // Increase roughness based on variance (simple approximation)
          float rr = r*r + variance;
          return clamp(sqrt(rr), 0.0, 1.0);
      }

      // Clamp a sample to the tile selected by the center UV. The center must
      // remain the anchor: clamping from the offset sample itself can move a
      // wide AA tap into a neighboring atlas tile.
      vec2 clampUvToTile(vec2 sampleUv, vec2 centerUv) {
          if (atlasSize <= 1.0) return sampleUv; // not an atlas: no clamp needed
          float tileW = 1.0 / atlasSize;
          float tileIndex = clamp(floor(centerUv.x / tileW), 0.0, atlasSize - 1.0);
          float uMin = tileIndex * tileW;
          float uMax = uMin + tileW;
          // Match mesher epsilon: half-pixel in UV space
          float epsU = 0.5 / (atlasSize * tileSize);
          float epsV = 0.5 / max(tileSize, 1.0);
          sampleUv.x = clamp(sampleUv.x, uMin + epsU, uMax - epsU);
          sampleUv.y = clamp(sampleUv.y, 0.0 + epsV, 1.0 - epsV);
          return sampleUv;
      }

      // Derivative-aware texture sampling to reduce minification shimmer
      // Provide LOD function with graceful fallback if the extension is missing
      #ifdef TEXTURE_LOD_EXT
      vec4 texLod2D(sampler2D tex, vec2 uv, float lod) { return texture2DLodEXT(tex, uv, lod); }
      #else
      vec4 texLod2D(sampler2D tex, vec2 uv, float lod) { return texture2D(tex, uv); }
      #endif

      // Combines 4-tap RGSS with a directional anisotropic kernel when footprint is elongated
      vec4 texture2D_AA(sampler2D tex, vec2 uv) {
          vec4 base = texture2D(tex, clampUvToTile(uv, uv));
          // The atlas intentionally has no mip chain or padded tile borders.
          // Any multi-tap filter can therefore turn a tiny change in the
          // projected footprint into a different mixture of nearest texels.
          // Keep atlas samples single-tap and stable; retain the derivative
          // filter below for standalone textures such as the seabed.
          if (!aaEnabled || atlasSize > 1.0) return base;

          // Estimate pixel footprint in texel units
          vec2 texSize = vec2(max(1.0, atlasSize * tileSize), max(1.0, tileSize));
          vec2 dx_uvt = dFdx(uv) * texSize;
          vec2 dy_uvt = dFdy(uv) * texSize;
          float lenx = length(dx_uvt);
          float leny = length(dy_uvt);
          float maxLen = max(lenx, leny);
          float minLen = max(min(lenx, leny), 1e-5);
          float aniso = maxLen / minLen;

          // Mix factor vs minification
          float k = smoothstep(1.0, 3.0, maxLen) * clamp(aaStrength, 0.0, 1.0);
          if (k <= 0.001) return base;

          // If footprint is strongly elongated, sample along its major axis (screen-aligned stripes case)
          if (aniso > 2.0) {
            // Keep the derivative magnitude. A normalized direction with a
            // raw ±0.5 UV offset spans most of the atlas instead of one pixel.
            vec2 majorDerivative = (lenx > leny) ? dFdx(uv) : dFdy(uv);

            // 7- or 9-tap kernel depending on minification (clamped)
            int taps = (maxLen > 6.0) ? 9 : 7;
            float halfT = float(taps - 1) * 0.5;

            // Cover the pixel footprint width (±0.5 along major) with a Gaussian
            vec4 sum = vec4(0.0);
            float wsum = 0.0;
            for (int i = 0; i < 9; i++) {
              if (i >= taps) break;
              float fi = float(i) - halfT;       // [-halfT, halfT]
              float t = fi / max(halfT, 1.0);    // [-1, 1]
              float w = exp(-t*t * 3.0);         // Gaussian-ish weights
              vec2 o = majorDerivative * (t * 0.5); // ±0.5 pixel footprint
              // On non-atlas textures (single image with mipmaps), push a slight lod bias to avoid banding
              float lodBias = (atlasSize <= 1.0 && aaLodBiasEnabled) ? (aaLodBias * smoothstep(1.5, 8.0, maxLen)) : 0.0;
              vec4 c = texLod2D(tex, clampUvToTile(uv + o, uv), lodBias);
              sum += c * w; wsum += w;
            }
            vec4 anisoAvg = sum / max(wsum, 1e-5);
            return mix(base, anisoAvg, k);
          }

          // Otherwise use 4-tap rotated grid inside the pixel footprint (good isotropic prefilter)
          vec2 dx = dFdx(uv);
          vec2 dy = dFdy(uv);
          const float ofs = 0.35;
          vec2 o1 = ( dx + dy) * ofs;
          vec2 o2 = ( dx - dy) * ofs;
          vec2 o3 = (-dx + dy) * ofs;
          vec2 o4 = (-dx - dy) * ofs;

          float lodBiasIso = (atlasSize <= 1.0 && aaLodBiasEnabled) ? (aaLodBias * smoothstep(1.5, 8.0, maxLen)) : 0.0;
          vec4 c1 = texLod2D(tex, clampUvToTile(uv + o1, uv), lodBiasIso);
          vec4 c2 = texLod2D(tex, clampUvToTile(uv + o2, uv), lodBiasIso);
          vec4 c3 = texLod2D(tex, clampUvToTile(uv + o3, uv), lodBiasIso);
          vec4 c4 = texLod2D(tex, clampUvToTile(uv + o4, uv), lodBiasIso);
          vec4 avg4 = (c1 + c2 + c3 + c4) * 0.25;
          return mix(base, avg4, k);
      }

      vec4 calculateEnhancedLighting(vec3 albedo, vec3 normal, vec3 viewDir, float ambientOcclusion) {
          // Ambient visibility is kept separate from direct sun lighting.
          vec3 starAmb = vec3(0.02, 0.025, 0.04) * 0.35 * clamp(starLight, 0.0, 1.0);
          float ao = clamp(ambientOcclusion, 0.0, 1.0);
          vec3 ambient = (skyAmbient + starAmb) * ao;
          
          // Main sun light (provided via uniforms)
          vec3 sunDir = normalize(sunDirection);
          float sunDot = max(dot(normal, sunDir), 0.0);
          
          // Use the screen-space voxel DDA visibility mask only for direct sun
          // diffuse. The post-process SSAO mask is derived below from the
          // unshadowed lighting, so shadow coverage cannot amplify screen-space
          // AO at cube edges.
          float shadowFactor = getVoxelShadowMask();
          
          // Apply shadow to diffuse lighting
          // Crisper sun diffuse for stronger, clearer shadows
          float wrappedDiffuse = sunDot;
          vec3 unshadowedDiffuse = sunColor * wrappedDiffuse * clamp(dayLight, 0.0, 1.0);
          vec3 diffuse = unshadowedDiffuse * shadowFactor;
          
          // Fresnel rim lighting
          float fresnel = pow(1.0 - max(dot(normal, viewDir), 0.0), 2.0);
          vec3 fresnelColor = vec3(0.8, 0.9, 1.0) * fresnel * 0.2 * clamp(dayLight, 0.0, 1.0) * ao;
          
          // Environment reflection (only if envMap is available)
          vec3 reflection = vec3(0.0);
          #ifdef USE_ENVMAP
            vec3 reflectDir = reflect(-viewDir, normal);
            vec3 envColor = textureCube(envMap, reflectDir).rgb;
            float roughAA = specularAARoughness(roughness, normal);
            reflection = envColor * envMapIntensity * (1.0 - roughAA) * fresnel * clamp(dayLight, 0.0, 1.0) * ao;
          #endif
          
          // Subsurface scattering
          float backLight = max(dot(normal, -sunDir), 0.0);
          vec3 subsurface = sunColor * backLight * 0.1 * (1.0 - metalness) * clamp(dayLight, 0.0, 1.0);
          
          vec3 indirect = ambient + fresnelColor + reflection;
          vec3 total = indirect + diffuse + subsurface;
          float indirectLuma = dot(max(indirect, vec3(0.0)), vec3(0.2126, 0.7152, 0.0722));
          // This mask is consumed by SSAOPass through the opaque alpha
          // channel. Use the unshadowed direct contribution as its reference
          // so it remains invariant when the voxel visibility mask changes.
          vec3 shadowIndependentTotal = indirect + unshadowedDiffuse + subsurface;
          float shadowIndependentLuma = dot(max(shadowIndependentTotal, vec3(0.0)), vec3(0.2126, 0.7152, 0.0722));
          float indirectMask = clamp(indirectLuma / max(shadowIndependentLuma, 1e-4), 0.0, 1.0);
          return vec4(total, indirectMask);
      }

      float waterCausticField(vec2 worldXZ, float time) {
          vec2 p = worldXZ * 0.34;
          float bendA = 0.55 * sin(dot(p, vec2(0.31, 0.47)) + time * 0.12);
          float bendB = 0.42 * sin(dot(p, vec2(-0.53, 0.27)) - time * 0.08);
          float ridgeA = 1.0 - smoothstep(0.035, 0.24, abs(sin(dot(p, vec2(1.63, 2.21)) + bendA)));
          float ridgeB = 1.0 - smoothstep(0.035, 0.24, abs(sin(dot(p, vec2(-2.07, 1.19)) + bendB)));
          float ridgeC = 1.0 - smoothstep(0.035, 0.24, abs(sin(dot(p, vec2(0.79, -2.67)) + bendA * 0.6 - bendB * 0.3)));
          return clamp(max(max(ridgeA, ridgeB * 0.88), ridgeC * 0.72), 0.0, 1.0);
      }

      // The caustic pass is a differential-area projection of the live wave
      // surface.  Sample three nearby channels so the focused web has the
      // slight chromatic separation seen through real water.  The source is a
      // world-anchored 17 m tile, so wrapping (rather than clamping to a
      // camera-following rectangle) keeps the pattern continuous at the map
      // boundary and prevents the old snap-induced flashes.
      vec3 sampleWaterCaustics(vec2 worldXZ) {
          vec2 causticCoord = (worldXZ - waterCausticOrigin) / max(waterCausticExtent, 1.0) + 0.5;
          vec2 uv = fract(causticCoord);
          vec2 texel = 1.0 / max(waterCausticResolution, vec2(1.0));
          float footprint = max(length(dFdx(causticCoord)), length(dFdy(causticCoord))) * max(waterCausticResolution.x, waterCausticResolution.y);
          float footprintFade = 1.0 - smoothstep(1.2, 5.0, footprint);
          float r = texture2D(waterCausticMap, fract(uv + texel * vec2(0.65, -0.45))).r;
          float g = texture2D(waterCausticMap, fract(uv + texel * vec2(-0.35, 0.70))).r;
          float b = texture2D(waterCausticMap, fract(uv + texel * vec2(-0.85, -0.25))).r;
          return mix(vec3(0.18), vec3(r, g, b), footprintFade);
      }

      void main() {
          vec4 texColor = texture2D_AA(map, vUv);
          // Atlas textures are uploaded as SRGBColorSpace; WebGL performs the
          // transfer-function decode during sampling, so this value is already
          // scene-linear and must not be decoded a second time.
          vec3 albedo = texColor.rgb;
          vec3 tinted = albedo * vColor;
          
          vec3 normal = normalize(vNormal);
          vec3 viewDir = normalize(cameraPosition - vWorldPosition);
          
          vec4 lighting = calculateEnhancedLighting(tinted, normal, viewDir, vAmbientOcclusion);
          vec3 lit = lighting.rgb * tinted;
          vec3 color = mix(tinted, lit, clamp(lightingMix, 0.0, 1.0));

          if (waterCausticEnabled) {
            float submerged = 1.0 - smoothstep(waterCausticLevel - 0.75, waterCausticLevel + 0.25, vWorldPosition.y);
            float upward = smoothstep(0.10, 0.85, max(vNormal.y, 0.0));
            float depthFade = exp(-max(waterCausticLevel - vWorldPosition.y, 0.0) * 0.055);
            if (waterCausticMapEnabled) {
              vec3 caustic = sampleWaterCaustics(vWorldPosition.xz);
              float gain = max(dot(caustic, vec3(0.2126, 0.7152, 0.0722)) - 0.18, 0.0);
              float response = gain * submerged * upward * depthFade * waterCausticIntensity;
              color *= 1.0 + response * 0.85;
              color += vec3(0.025, 0.090, 0.115) * response;
            } else {
              float caustic = waterCausticField(vWorldPosition.xz, waterCausticTime);
              color += vec3(0.06, 0.16, 0.18) * caustic * submerged * upward * waterCausticIntensity;
            }
          }
          
          // Small blue-noise-ish dithering in scene-linear space to reduce
          // visible banding before the shared output transform.
          if (ditherAmount > 0.0) {
            float n1 = fract(sin(dot(gl_FragCoord.xy, vec2(12.9898,78.233))) * 43758.5453);
            float n2 = fract(sin(dot(gl_FragCoord.yx, vec2(39.3467,11.135))) * 24634.6345);
            float tri = (n1 + n2) - 1.0; // triangular distribution in [-1,1]
            float amp = (ditherAmount / 255.0); // ~1 LSB at 1.0
            color += tri * amp;
          }

          // Opaque block pixels use alpha as an internal indirect-light mask
          // for the post-process SSAO pass. This material is never blended.
          float indirectMask = lighting.a * clamp(lightingMix, 0.0, 1.0);
          gl_FragColor = vec4(color, 1.0 - indirectMask);
      }
    `;

    super({
      vertexShader,
      fragmentShader,
      uniforms: THREE.UniformsUtils.merge([
        {
          map: { value: albedoTexture },
          normalMap: { value: normalMap || null },
          envMap: { value: envMap },
          roughness: { value: 0.8 },
          metalness: { value: 0.0 },
          envMapIntensity: { value: 0.3 },
          alphaScale: { value: 1.0 },
          lightingMix: { value: 1.0 },

          // Sun uniforms (updated by Engine via SunController)
          sunDirection: { value: new THREE.Vector3(50, 120, 50).normalize() },
          sunColor: { value: new THREE.Color(1.0, 0.95, 0.8) },
          voxelShadowMask: { value: createWhiteTexture() },
          voxelShadowResolution: { value: new THREE.Vector2(1, 1) },
          voxelShadowEnabled: { value: false },
          dayLight: { value: 1.0 },
          starLight: { value: 0.0 },
          skyAmbient: { value: new THREE.Color(0.12, 0.18, 0.32) },
          waterCausticEnabled: { value: false },
          waterCausticLevel: { value: 43.0 },
          waterCausticIntensity: { value: 0.0 },
          waterCausticTime: { value: 0.0 },
          waterCausticMap: { value: createWhiteTexture() },
          waterCausticMapEnabled: { value: false },
          waterCausticOrigin: { value: new THREE.Vector2(0, 0) },
          waterCausticExtent: { value: 256.0 },
          waterCausticResolution: { value: new THREE.Vector2(256, 256) },
          // Anti-aliasing defaults
          aaEnabled: { value: true },
          aaStrength: { value: 1.0 },
          aaLodBiasEnabled: { value: true },
          aaLodBias: { value: 0.9 },
          atlasSize: { value: (atlasInfo?.atlasSize ?? 1) },
          tileSize: { value: (atlasInfo?.tileSize ?? 16) },
          ditherAmount: { value: 0.75 },
          voxelShadowDepth: { value: createWhiteTexture() },
          voxelShadowCameraNear: { value: 0.1 },
          voxelShadowCameraFar: { value: 1024.0 }
        }
      ]),
      defines: envMap ? { USE_ENVMAP: true } : {},
      side: THREE.FrontSide,
      transparent: false,
      toneMapped: false,
      // All illumination is authored in this shader. Native Three.js shadow
      // chunks are intentionally disabled; VoxelSunShadowPass owns visibility.
      lights: false,
    });
  }

  /**
   * Set material properties
   */
  setMaterialProperties(roughness: number, metalness: number, envMapIntensity: number): void {
    const uniforms = this.uniforms as Record<string, { value: unknown }>;
    uniforms.roughness.value = roughness;
    uniforms.metalness.value = metalness;
    uniforms.envMapIntensity.value = envMapIntensity;
  }

  setAlphaScale(a: number): void {
    const uniforms = this.uniforms as Record<string, { value: unknown }>;
    uniforms.alphaScale.value = THREE.MathUtils.clamp(a, 0, 1);
  }

  setLightingMix(t: number): void {
    const uniforms = this.uniforms as Record<string, { value: unknown }>;
    uniforms.lightingMix.value = THREE.MathUtils.clamp(t, 0, 1);
  }

  /** Configure in-shader anti-aliasing strength (0..1) and toggle */
  setAntialiasing(enabled: boolean, strength = 1.0): void {
    const u = this.uniforms as Record<string, { value: unknown }>;
    u.aaEnabled.value = !!enabled;
    u.aaStrength.value = THREE.MathUtils.clamp(strength, 0, 1);
  }

  /** Configure LOD bias AA (for non-atlas textures with mipmaps such as seabed sand) */
  setAALodBias(enabled: boolean, bias = 0.9): void {
    const u = this.uniforms as Record<string, { value: unknown }>;
    u.aaLodBiasEnabled.value = !!enabled;
    u.aaLodBias.value = THREE.MathUtils.clamp(bias, 0, 2);
  }

  /** Update atlas info (tile size/atlas size) to keep AA sampling stable */
  setAtlasInfo(info: { tileSize: number; atlasSize: number }): void {
    const u = this.uniforms as Record<string, { value: unknown }>;
    u.tileSize.value = Math.max(1, info.tileSize | 0);
    u.atlasSize.value = Math.max(1, info.atlasSize | 0);
  }

  /**
   * Update sun lighting uniforms (direction + color)
   */
  setSunUniforms(direction: THREE.Vector3, color: THREE.Color): void {
    const uniforms = this.uniforms as Record<string, { value: unknown }>;
    (uniforms.sunDirection.value as THREE.Vector3).copy(direction);
    (uniforms.sunColor.value as THREE.Color).copy(color);
  }

  /** Bind the screen-space visibility produced by VoxelSunShadowPass. */
  setVoxelShadowTexture(texture: THREE.Texture, width: number, height: number, enabled = true): void {
    const uniforms = this.uniforms as Record<string, { value: unknown }>;
    uniforms.voxelShadowMask.value = texture;
    (uniforms.voxelShadowResolution.value as THREE.Vector2).set(Math.max(1, width), Math.max(1, height));
    uniforms.voxelShadowEnabled.value = enabled;
  }

  /** Bind the shared depth prepass used to keep edge reconstruction local. */
  setVoxelShadowDepthTexture(texture: THREE.Texture, near: number, far: number): void {
    const uniforms = this.uniforms as Record<string, { value: unknown }>;
    uniforms.voxelShadowDepth.value = texture;
    uniforms.voxelShadowCameraNear.value = near;
    uniforms.voxelShadowCameraFar.value = far;
  }

  /**
   * Share the complete screen-space visibility binding with another block
   * receiver. Render-only terrain such as the ocean seabed must use the same
   * uniform objects, not a one-frame value copy: the mask target, resolution,
   * and depth attachment can all change during resize, while Composer
   * temporarily disables the shared binding during its opaque capture.
   */
  shareVoxelShadowState(source: BlockMaterial): void {
    const sourceUniforms = source.uniforms as Record<string, THREE.IUniform>;
    const targetUniforms = this.uniforms as Record<string, THREE.IUniform>;
    const keys = [
      'voxelShadowMask',
      'voxelShadowDepth',
      'voxelShadowResolution',
      'voxelShadowCameraNear',
      'voxelShadowCameraFar',
      'voxelShadowEnabled',
    ] as const;

    for (const key of keys) {
      targetUniforms[key] = sourceUniforms[key];
    }
  }

  /** Day/night factor (0=night, 1=day) */
  setDayLight(level: number): void {
    const uniforms = this.uniforms as Record<string, { value: unknown }>;
    uniforms.dayLight.value = THREE.MathUtils.clamp(level, 0, 1);
  }

  /** Star light factor (0..1) */
  setStarLight(level: number): void {
    const uniforms = this.uniforms as Record<string, { value: unknown }>;
    uniforms.starLight.value = THREE.MathUtils.clamp(level, 0, 1);
  }

  /** Update the shared scene-linear sky irradiance. */
  setSkyAmbient(color: THREE.Color): void {
    (this.uniforms.skyAmbient.value as THREE.Color).copy(color);
  }

  /** Enable the shared render-only water caustic response on submerged faces. */
  setWaterCaustics(enabled: boolean, waterLevel: number, intensity: number, time = 0): void {
    const uniforms = this.uniforms as Record<string, { value: unknown }>;
    uniforms.waterCausticEnabled.value = enabled;
    uniforms.waterCausticLevel.value = waterLevel;
    uniforms.waterCausticIntensity.value = Math.max(0, intensity);
    uniforms.waterCausticTime.value = time;
  }

  /** Bind the render-only differential-area caustic field. */
  setWaterCausticTexture(texture: THREE.Texture | null, origin: { x: number; y: number }, extent: number, resolution: { x: number; y: number }): void {
    const uniforms = this.uniforms as Record<string, { value: unknown }>;
    uniforms.waterCausticMap.value = texture;
    uniforms.waterCausticMapEnabled.value = !!texture;
    (uniforms.waterCausticOrigin.value as THREE.Vector2).set(origin.x, origin.y);
    uniforms.waterCausticExtent.value = Math.max(1, extent);
    (uniforms.waterCausticResolution.value as THREE.Vector2).set(Math.max(1, resolution.x), Math.max(1, resolution.y));
  }

}
